### ISSUE TITLE
ImageSeriesReader.GetGDCMSeriesFileNames does not expect arguments

### ISSUE THREAD

**Issue by haarburger** [SimpleITK/SimpleITK#112]
If I load frames from a directory `fpath`,

```python
reader = sitk.ImageSeriesReader()
filenames = reader.GetGDCMSeriesFileNames(fpath, loadPrivateTags=True)
reader.SetFileNames(filenames)
img = reader.Execute()
```
gives me
```
GetGDCMSeriesFileNames() got an unexpected keyword argument 'loadPrivateTags'
```

Setting `reader.SetLoadPrivateTags(True)` and `reader.LoadPrivateTagsOn()` had no effect. (What's the difference btw?)

I tested with Python 3.5 (Anaconda), Ubuntu 16.04, SimpleITK versions 0.10.0 and 1.0.0rc1+g57b8f.

**Comment by zivy** [comment]
Multi part answer, skip to 3 for a solution (1,2 are explanations):
1. The error you are encountering is due to a limitation of SWIG with respect to overloaded functions in C++. The Python keyword parameters don't work (place works fine, but that is not what you wanted).

2. The 'loadPrivateTags' in the GetGDCMSeriesFileNames should not have been exposed, it doesn't have an effect on the returned series file names. We should set it to false internally so that private tags aren't read when reading the meta-data dictionary as we are only looking at the study-series information to identify a series. I will fix this shortly.

3. A possible solution assuming you want to read a series and access the meta-data:
a. When reading a series in SimpleITK all of the meta-data is lost (img.GetMetaDataKeys() will return an empty tuple).
b. The GetGDCMSeriesFileNames has two versions, the one you tried without specifying the series will return the file names associated with the first series encountered in the directory, the other option will get the series you specify.
c. To get the meta-data information you will have to read each file separately. 

A Jupyter notebook that illustrates loading a specific DICOM series is available [here](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/61_Registration_Introduction_Continued.ipynb). 

Loading a specific series from a directory containing multiple series:
```
reader = sitk.ImageSeriesReader()
seriesIDs = reader.GetGDCMSeriesIDs(data_directory) 
# User selects one of these series somehow, possibly based on meta-data 
series_index = 0
series_file_names = reader.GetGDCMSeriesFileNames(data_directory, seriesIDs[series_index])
reader.SetFileNames(series_file_names)
img = reader.Execute()
```

Getting the meta-data including private tags from a single image:
```
reader = sitk.ImageFileReader()
reader.LoadPrivateTagsOn()
reader.SetFileName(file_name)
img = reader.Execute()
img.GetMetaDataKeys()
```

**Comment by haarburger** [comment]
Thanks for the explanations in 1, 2! 

The possible solution you described in 3 is actually how I worked my way around the issue.

**Comment by zivy** [comment]
You're welcome. I am closing this issue.

**Comment by mikbuch** [comment]
Just a quick comment, because I had a similar issue: I have been getting `sitk::ERROR: File names information is empty. Cannot read series.` error because I was using path to the higher-level directory as an argument to the `reader.GetGDCMSeriesFileNames`. It turns out that `SimpleITK` won't search for the files in the subdirectories, so you have to specify the path to the "lowest" directory containing the files.
