### ISSUE TITLE
BinaryThresholdImageFilter returns ones image from zeros image

### ISSUE THREAD

**Issue by ctorti** [SimpleITK/SimpleITK#1277]
Hi all,

I wasn't expecting to pass an empty image to `BinaryThresholdImageFilter` but I did, and am surprised to find that the image that results from binary thresholding is effectively a ones image.  The code I've used is as follows:

```
import SimpleITK as sitk
BinThreshImFilt = sitk.BinaryThresholdImageFilter()
BinThreshImFilt.SetLowerThreshold(Thresh)
BinThreshImFilt.SetOutsideValue(0)
BinThreshImFilt.SetInsideValue(1)
BinIm = BinThreshImFilt.Execute(Im)
```

where `Thresh` is the thresold value (e.g. 0.5), and `Im` is the image to be binary thresholded.

Is this behaviour expected?

The only situation that I can foresee where a zeros image might be binary thresholded to a ones image is if I were to set `SetUpperThreshold` to a value greater than 0, and avoided setting `SetLowerThreshold`.  I tried that and got the same result, so it's difficult to ascertain what's going on.

**Comment by blowekamp** [comment]
To see the internals of the ITK filter execution you can set `DebugOn()`. This should show that "LowerThreshold" has been rounded to "0".

**Comment by ctorti** [comment]
Thanks.  Unfortunately I don't get any output logged to the (Anaconda Jupyter notebook) console when I set `DebugOn()`.

So if it is the case that `SetLowerThreshold` is being rounded to 0, is it possible to set a threshold between 0 and 1 for binary images, or some other means of doing the same using a different filter?

You may be wondering why would I want to do this if the image is binary.  I should probably explain where I'm going with this:  I've found that when resampling an image from a low-to-high-voxel-spacing image, I am able to resample a binary image - say a 3D image with a single non-zero mask on a particular slice, to a new binary image that contains a non-zero mask on more than one slice.

However I run into problems when trying to resample from a high-to-low-voxel-spacing image.  It's possible for me to get a completely empty resampled image.  I'm working with DICOM images, so perhaps what can happen is the mask I am trying to resample is falling (or partially falling) within the gap between slices in the lower-resolution image.

If that's the case, I'm guessing that the degree of overlap between the original voxels and the voxels in the new image space is too small to be considered a "1".  I'm guessing that the NearestNeighbor interpolation is performing rounding and assigns a 0 to overlaps, say, less than 50% of the volume of the voxel in the new image space.

If all of that is true, my intended work around is to resample using a linear or BSpline interpolation, then binary threshold the resampled image, but less aggressively than 0.5.  But if I can't binary threshold at a value less than 1, I'll have to find another way.

In addition to helping me to understand how to binary threshold at a value <1 I would be very greatful if anyone can provide any comments on why I might be getting empty resampled images, if my hypothesis is correct, and is my workaround sensible (and if not, any alternative suggestions).

Thanks very much.

**Comment by zivy** [comment]
Hello @ctorti,

What you are experiencing when resampling a signal using a smaller grid size (larger spacing) is known as [aliasing](https://en.wikipedia.org/wiki/Aliasing). You have a signal with high frequencies (binary segmentation) and the sampling rate is not sufficiently high ([Nyquist theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem)), so the segmentation mask "disappeared" in the resulting image.

Several options for dealing with this (reduce the high frequency components of the original image). Lets assume that the segmentation label is 1:
1. Use the sitkLabelGaussian interpolator.
2. Gaussian blur the segmentation, then resample using a linear interpolator, and then threshold so that values in [a<1<b] are mapped to 1. You will need to select appropriate values for a, b.
3. Compute the distance map of the segmentation, then resample using a linear interpolator, and then threshold the absolute value of the distance map (`sitk.Abs(lowres_distance_map)<dist_threshold`). Again, you need to select an appropriate dist_threshold.

These solutions mitigate the problem, but there is no guarantee if the resampling rate is not sufficiently high.

**Comment by ctorti** [comment]
Hi @zivy thank you very much for your help.

I never considered that this issue was down to an aliasing/undersampling problem!

I tried the simplest of the three solutions you proposed (option 1) but that didn't help.  But with an appropriate thresholding value I got the second solution to work.  I'm a bit uncomfortable about the rather trial-and-error approach I've taken to set the threshold level.  Perhaps running this through more examples will reveal a more deterministic way of going about things.

I'll close this now.

**Comment by gdevenyi** [comment]
> 1. Use the sitkLabelGaussian interpolator.

Suggest instead, https://itk.org/Doxygen/html/group__GenericLabelInterpolator.html

**Comment by ctorti** [comment]
Thanks @gdevenyi for the suggestion but it seems that interpolator isn't available for SimpleITK.  Unless I'm wrong?

**Comment by gdevenyi** [comment]
Ah, seems it hasn't been wrapped yet. I usually consider ITK and SimpleITK to be equivalent, sometimes forget they're not. Sorry.

**Comment by ctorti** [comment]
I appreciate your attempt to help nonetheless. 👍
