### ISSUE TITLE
Can't set proper path for ImageJ 

### ISSUE THREAD

**Issue by makquel** [SimpleITK/SimpleITK#1278]
Hi, 

I've been struggling with Fiji integration with the latest version of SimpleITK. It's seems that in the previous version (e.g. 1.2.4) was more straight forward. So here is the deal, I've downloaded the latest ImageJ, exported the PATH to my bashrc and even created a soft-link to ImageJ binaries, however, couldn't solve the related issue. Is there any way to hardcde it to point the proper path?

And BTW, sorry if this was a issue before, couldn't find it though.

**Comment by zivy** [comment]
Hi @makquel,

I believe [this FAQ](https://simpleitk.readthedocs.io/en/master/faq.html#why-isn-t-fiji-or-imagej-found-by-the-show-function-runtimeerror-exception-thrown) addresses your issue. If yes, please close the issue. If not, please provide additional details (which of the options in the FAQ you used so that we can see why it didn't work in your case).

**Comment by makquel** [comment]
Hi @zivy,

I've followed most of steps of the discussion forums and also check the link that contains ImageJ binaries in my Linux machine. However, I can't still manage to get the proper path. Once I use de debug mode (`debugOn=True`) I get the following warning:
```shell
WARNING: In /usr/share/miniconda/envs/bld/conda-bld/simpleitk_1602769554837/work/build/ITK/Modules/IO/Meta/src/itkMetaImageIO.cxx, line 669
MetaImageIO (0x55ed9fac1ef0): Unsupported or empty metaData item aux_file of type NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEfound, won't be written to image file

WARNING: In /usr/share/miniconda/envs/bld/conda-bld/simpleitk_1602769554837/work/build/ITK/Modules/IO/Meta/src/itkMetaImageIO.cxx, line 669
MetaImageIO (0x55ed9fac1ef0): Unsupported or empty metaData item intent_name of type NSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEfound, won't be written to image file
```

This caused by a runtime error in my python script 
```shell
RuntimeError: Exception thrown in SimpleITK Show: ../../Code/IO/src/sitkImageViewer.cxx:620:
sitk::ERROR: No ImageJ/Fiji application found.
```

Do you have any idea of what could be causing this?

**Comment by zivy** [comment]
Hello @makquel,

Is Fiji installed in the directory ~/bin or is it somewhere else? You didn't specify.

**Comment by dave3d** [comment]
On Linux systems, SimpleITK is searching for the executable Fiji.app/ImageJ-linux64.  By default it looks the $HOME/bin, /opt, and /usr/local.

**Comment by makquel** [comment]
@zivy,

I installed the Fiji.app/ImageJ-linux64 in my $HOME folder, I also soft-linked the binary to a folder called $HOME/bin as @dave3d pointed out, however, is still launching the RuntimeError I mentioned before. I should try to do other workaround since this is no working for me.

**Comment by dave3d** [comment]
Have you tried using the SITK_SHOW_COMMAND environment variable?  Here's how I set it to point to the ImageJ executable:

`export SITK_SHOW_COMMAND=/home/dave/bin/Fiji.app/ImageJ-linux64
`

SimpleITK ought to find ImageJ without it, since it's in the expected location, but just try it out to see if it works.

**Comment by makquel** [comment]
Thanks @dave3d, setting the environment variable worked for me!
