### ISSUE TITLE
N4BiasFieldCorrectionImageFilter() does never converge

### ISSUE THREAD

**Issue by wwaleww** [SimpleITK/SimpleITK#1344]
Hello,

I'm trying to apply the `sitk.N4BiasFieldCorrectionImageFilter()` on some MRI DICOM images, with the following code:

```
import SimpleITK as sitk

corrector = sitk.N4BiasFieldCorrectionImageFilter()

shrink_factor = 4
image_shrinked = sitk.Shrink( image, [shrink_factor] * dors_sitk.GetDimension())

numberFittingLevels = 4
numberOfIteration = [50,40,30]

corrector.SetBiasFieldFullWidthAtHalfMaximum ( 0.15 )
corrector.SetConvergenceThreshold( 0.001 )
corrector.SetSplineOrder( 3 )
corrector.SetMaximumNumberOfIterations(numberOfIteration * numberFittingLevels)

output = corrector.Execute( image_shrinked )
```

where the `image` variable is a SimpleITK volume of images casted to `sitkFloat32`. I don't get any error with the parameters I set, but it just executes forever, and never converging. I tried to play a bit with the parameters, but didn't manage to make it work.
Is there anything I'm doing wrong?

Thank you in advance!

**Comment by zivy** [comment]
Hello @wwaleww,

I suspect the issue is with your call to `SetMaximumNumberOfIterations`. The list you are passing is very long `[50, 40, 30, 50, 40, 30, 50, 40, 30, 50, 40, 30]`. If you are basing this code off of the [example code](https://simpleitk.readthedocs.io/en/master/link_N4BiasFieldCorrection_docs.html), that used list multiplication to replicate a scalar based on the number of fitting levels. So with an input of max iterations of 20 the example code calls the `SetMaximumNumberOfIterations` with a parameter of  `[20, 20, 20, 20]`.

**Comment by wwaleww** [comment]
Indeed that was the problem, now it runs very quickly, thanks a lot! :)
