### ISSUE TITLE
N4BiasFieldCorrection TypeError: Wrong number or type of arguments for overloaded function 'N4BiasFieldCorrectionImageFilter_Execute'.

### ISSUE THREAD

**Issue by mistermoutan** [SimpleITK/SimpleITK#1389]
I am trying to use N4BiasFieldCorrection exactly as in the example provided here: https://simpleitk.readthedocs.io/en/master/link_N4BiasFieldCorrection_docs.html

I load the original volume as well as the segmentation mask as in:    

```
import numpy as np
import SimpleITK as sitk

corrector = sitk.N4BiasFieldCorrectionImageFilter()

shape = (120, 130, 130)

#generate arrays
r1 = np.random.randn(*shape)
r2 = np.random.randint(2, size=120 * 130 * 130) #binary array 
r2 = np.reshape(r2, (120, 130, 130))

itk_img = sitk.GetImageFromArray(r1)
itk_mask = sitk.GetImageFromArray(r2)

corrected_image = corrector.Execute(image, itk_mask)
```

`itk_img` is of type 32-bit float and `itk_mask` of 8-bit unsigned integer. I get the following error:

```
TypeError: Wrong number or type of arguments for overloaded function 'N4BiasFieldCorrectionImageFilter_Execute'.
  Possible C/C++ prototypes are:
    itk::simple::N4BiasFieldCorrectionImageFilter::Execute(itk::simple::Image const &,itk::simple::Image const &)
    itk::simple::N4BiasFieldCorrectionImageFilter::Execute(itk::simple::Image const &)
```
Alternatively, if I try to arrive at the mask with:

`itk_mask = sitk.OtsuThreshold(itk_img, 0, 1, 200)`

I get the same error. Any idea what the issue may be? I am using version: SimpleITK-2.1.0rc1.post2

**Comment by blowekamp** [comment]
There appear to be a discrepancy in you code. You set `itk_mask` yet you use `itk_label`. Additionally you have created an object `corrector` but it is not in the code.

Please try to create a minimal reproducible example of the issue where the input images are constructed ( not read ) as the same type and size as what is the the image file. The code should be self contained so that I could pasted it into Python and reproduce the problem.

**Comment by mistermoutan** [comment]
I had a mistake in the naming of my variables. It works as it should, I apologize.
