### ISSUE TITLE
Question: Registration of .bmp and .dcm

### ISSUE THREAD

**Issue by Fittrue** [SimpleITK/SimpleITK#1419]
Hello，

I am a SimpleITK beginner, I encountered a medical image registration problem. For some reasons, the storage became BMP format. I want to know how BMP files and dcm files are registered.

I'm using SimpleITK v 2.0.2 and the method is as follows:

```python
import SimpleITK as sitk

img1 = sitk.ReadImage('0003_1.bmp')
img2 = sitk.ReadImage('Flair3.dcm')

sitk.WriteImage(img1, '0003_1.nii.gz')
sitk.WriteImage(img2, 'flair3.nii.gz')

img11 = sitk.ReadImage('0003_1.nii.gz')
img22 = sitk.ReadImage('flair3.nii.gz')

# origin = img11.GetOrigin()
# origin2 = img22.GetOrigin()
# direction = img11.GetDirection()
# direction2 = img22.GetDirection()
# spacing = img11.GetSpacing()
# spacing2 = img22.GetSpacing()

img22.SetOrigin(img11.GetOrigin())
img22.SetDirection(img11.GetDirection())
img22.SetSpacing(img11.GetSpacing())

```
When i was debugging, I found `img11.Getorigin()` was different of `img22.GetOrigin()` , `GetDirection()` and `GetSpacing()` is the same question.

![debug](https://user-images.githubusercontent.com/31371538/124540282-ac568280-de51-11eb-89a1-f7a658be315b.png)
![debug2](https://user-images.githubusercontent.com/31371538/124540285-ae204600-de51-11eb-97fc-aab78c92a1a1.png)

Could someone please give me some suggestions?

**Comment by Fittrue** [comment]
this is the Run error.
![image](https://user-images.githubusercontent.com/31371538/124541000-1e7b9700-de53-11eb-85df-834e5d8f5b98.png)

**Comment by zivy** [comment]
Hello @Fittrue,

The input data is a bit strange. It appears that one image is read from a BMP format file, this means it is a 2D image with a pixel spacing of [1,1]. If this represents a physical object the original sizes were lost when it was saved using the BMP format. The DICOM format keeps the spatial information intact. As you can see, you have a 2D image but it is positioned in 3D, origin, direction cosine and spacing. Because it is a single slice the spacing in the third dimension defaults to 1. 

To register these images as 2D images you will need to "convert" the 3D image to 2D, `img2 = sitk.ReadImage('Flair3.dcm')[:,:,0]`.

Highly recommend reading the toolkit's [fundamental concepts](https://simpleitk.readthedocs.io/en/master/fundamentalConcepts.html), [registration overview](https://simpleitk.readthedocs.io/en/master/registrationOverview.html), and possibly go over the relevant [Jupyter notebooks](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks).

If you have the time, possibly take the [online tutorial](https://simpleitk.org/TUTORIAL/).

**Comment by Fittrue** [comment]
Thanks bro @zivy ,

your suggestions `img2 = sitk.ReadImage('Flair3.dcm')[:,:,0]` is worked, but it doesn't slove my problem, I want to rotate the picture to the same position, I think I should search the document about the rigid registration.

Thanks for your advice.
