### ISSUE TITLE
SimpleITK, ITK and Examples cannot be built

### ISSUE THREAD

**Issue by YBurakD** [SimpleITK/SimpleITK#1423]
Hi.
I am trying to build SimpleITK to use it with C++.  I have tried to build on Windows 10 with Visual Studio 2019, following the guide on https://simpleitk.readthedocs.io/en/master/buildingWindows.html . I have done everything that is written in the document and nothing else. To provide some more information, here is the result after configuring and generating build files with Cmake 3.19.4

![image](https://user-images.githubusercontent.com/32135008/126108111-cfcddc45-c2ec-4ecd-ad0e-f9d2035fa428.png)

After this, I build the ALL_BUILD.vcxproj with release mode and I get following errors:

![image](https://user-images.githubusercontent.com/32135008/126107708-1587c3f6-4436-42a2-8c66-f0b128cadfb2.png)

I am unable to see something out of ordinary so any help would be appreciated.

**Comment by dave3d** [comment]
It's hard to see what the problem is from just your screen capture.  Could you try building SimpleITK from the command line and then sharing the entire output here?

To build from the command line open up Windows PowerShell and enter this:

    cd C:\Users\YBurakD\Desktop\SimpleITK\SimpleITK-build
    cmake --build . --config Release

Also, as described in the instructions, it's better to not place the build directory so deep in the file system.  CMake can have problem with long path names.  It's better to have the build directory be something like C:\SimpleITK-build, right at the top of the file system.
