### ISSUE TITLE
MedianProjectionImageFilter broken on 4D image?

### ISSUE THREAD

**Issue by Gab-D-G** [SimpleITK/SimpleITK#1426]
Hi, I am trying to concatenate 3D images along the 4th axis using JoinSeriesImageFilter, and the compute their median using MedianProjectionImageFilter, but I get the following error:

```
>>> img1=sitk.ReadImage('../../rabies_out_updated/7_Cryo_med_f3/bold_datasink/inho_cor_bold//_scan_info_subject_id211.session1.runNone_split_name_sub-211_ses-1_task-rest_acq-EPI_bold/sub-211_ses-1_task-rest_acq-EPI_bold_inho_cor.nii.gz')
>>> join = sitk.JoinSeriesImageFilter()
>>> joined = join.Execute(img1,img1)
>>> median=sitk.MedianProjectionImageFilter()
>>> median.SetProjectionDimension(3)
>>> median.Execute(joined)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cic/desgab/miniconda3/envs/rabies/lib/python3.9/site-packages/SimpleITK/SimpleITK.py", line 17479, in Execute
    return _SimpleITK.MedianProjectionImageFilter_Execute(self, image1)
RuntimeError: Exception thrown in SimpleITK MedianProjectionImageFilter_Execute: ../Code/Common/include/sitkMemberFunctionFactory.hxx:155:
sitk::ERROR: Pixel type: 32-bit float is not supported in 4D by N3itk6simple27MedianProjectionImageFilterE.
>>> 
```

Changing the pixel type does not seem to solve the issue. 
```
>>> join = sitk.JoinSeriesImageFilter()
>>> joined = join.Execute(img1,img1)
>>> sitk.WriteImage(joined, 'temp.nii.gz')
>>> joined = sitk.ReadImage('temp.nii.gz', sitk.sitkInt32)
>>> median=sitk.MedianProjectionImageFilter()
>>> median.SetProjectionDimension(3)
>>> median.Execute(joined)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cic/desgab/miniconda3/envs/rabies/lib/python3.9/site-packages/SimpleITK/SimpleITK.py", line 17479, in Execute
    return _SimpleITK.MedianProjectionImageFilter_Execute(self, image1)
RuntimeError: Exception thrown in SimpleITK MedianProjectionImageFilter_Execute: ../Code/Common/include/sitkMemberFunctionFactory.hxx:155:
sitk::ERROR: Pixel type: 32-bit signed integer is not supported in 4D by N3itk6simple27MedianProjectionImageFilterE.
>>> 

```
Any idea what could be causing this? Thank you, Gabriel D-G

**Comment by zivy** [comment]
Hello @Gab-D-G,

Unfortunately, the error message is misleading. The problem is that currently the `MedianProjectionImageFilter` only supports 2D and 3D images, see code below:
```
import SimpleITK as sitk

image_3D = sitk.Image([32]*3, sitk.sitkUInt8)
image_4D = sitk.JoinSeries([image_3D]*5)
# Change the following line to run with the 4D image
image = image_3D
sitk.MedianProjection(image, image.GetDimension()-1)
```
As you want it in 4D, please create a feature request for this and we will look into it.

**Comment by gdevenyi** [comment]
@zivy to clarify here, is this a SimpleITK limitation, or an ITK limitation?

**Comment by zivy** [comment]
Hi @gdevenyi,

This is a feature/limitation of SimpleITK, which is why I asked for an official "feature request". 

The original philosophy/thinking underlying the design of SimpleITK is that for 95% of the work 2D and 3D images/filters are sufficient. This deviates from the original ITK thinking that everything is n-dimensional. By default, expect SimpleITK to support 2D and 3D. Over time, based on concrete needs we have increased dimensionality support for some operations (up to 5D). To keep to our underlying design principles we only increase the dimensionality when there is a specific, concrete need, not for hypothetical use cases. 

Beyond the philosophical reasoning, this also increases the binary size when instantiating all combinations of pixel-type and dimensionality using the underlying ITK templates.

Hope this clarifies things.

**Comment by gdevenyi** [comment]
Thanks, I was aware of the intentional 2D/3D limit, I just wasn't sure it was what applied in this case.
