### ISSUE TITLE
ImageSeriesReader creates images with different origins when not used with GetGDCMSeriesFileNames

### ISSUE THREAD

**Issue by zemmyang** [SimpleITK/SimpleITK#1609]
Scenario: I have a folder with DICOM files from one series. 
SimpleITK version: 2.0.2

If I use
```
reader = sitk.ImageSeriesReader()
dicom_names = reader.GetGDCMSeriesFileNames(dicomdir)
reader.SetFileNames(dicom_names)
image = reader.Execute()
image.GetOrigin()
```
the origin I get is the same as ITKSnap (3.8.0).

But when I use
```
from glob import glob

reader = sitk.ImageSeriesReader()
dicom_list = glob(f'{dicomdir}/*')
reader.SetFileNames(dicom_list)
image = reader.Execute()
image.GetOrigin()
```
I get the wrong origin. (This example might look clunky and inconvenient, but I generally deal with folders with DICOM files from many sequences and my program generates a saved list saying which files belong to which sequence, whch works pretty well)

I checked if I get the same list of files from both functions (`set([os.path.basename(i) for i in dicom_names]) == set([os.path.basename(i) for i in dicom_list])`) and I get True. I even tried making dicom_list match dicom_names exactly (using `dicom_list = [f'{os.path.dirname(i)}/{os.path.basename(i)}' for i in glob(f'{dicomdir}/*')]`) and the origin is still wrong.

Why is this so? 

----

fwiw: The current code block in my program goes like
````
def get_sitk_image(file_list: list):
        reader = sitk.ImageSeriesReader()

        with tempfile.TemporaryDirectory() as temp_dir:
            for fi in file_list:
                shutil.copy(src=fi, dst=temp_dir)

            dicom_names = reader.GetGDCMSeriesFileNames(temp_dir)
            reader.SetFileNames(dicom_names)
            image = reader.Execute()

        return image
````
which is significantly slower compared to the original-but-somehow-wrong function:
```
def get_sitk_image(file_list: list):
    reader = sitk.ImageSeriesReader()
    reader.SetFileNames(file_list)
    return reader.Execute()
```

**Comment by zivy** [comment]
Hello @zemmyang,

The `ImageSeriesReader` expects the file list to be ordered along the scanning axis. Using `glob` returns the files ordered according to file name and has nothing to do with the order along the axis. In many cases the file names are in order according to the scan axis, so `glob` looks like it is returning the correct order but it is just a coincidence.

Generally speaking, a DICOM series does not have to reside in a single directory. This means that you can have duplicate file names in the same series (often happens when the data is burned to CD):
```
data/
├── series1a/
│   ├── z0
│   ├── z1
│   └── z2
│   
└── series1b/
   ├── z0
   └── z1
```
To deal with the generic situation and enable reading with SimpleITK you need all the files to reside in a single directory (limitation of `GetGDCMSeriesFileNames`), so you either need to copy and rename them or create a soft link. Please take a look at [this code](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/448d3c18dbe0b388f7a41080dcb33a46cd05f0aa/Python/characterize_data.py#L278-L398) which deals with all of these situations. 

Unfortunately, on windows you will be copying files and that takes a while as compared to creating symbolic links which works on OSX and linux. If you find a better way of doing this on windows let us know.

**Comment by zemmyang** [comment]
Hi @zivy, thanks for the explanation.

Bit of a stupid question, but is there a way to reorder the file list according to the scanning axis without using `GetGDCMSeriesFileNames`?
