### ISSUE TITLE
SimpleITK VersorRigid3DTransform_SetMatrix ignores tolerance parameter.

### ISSUE THREAD

**Issue by pezize** [SimpleITK/SimpleITK#1616]
**Description**
Provide VersorRigid3DTransform_SetMatrix with a matrix representing a rotation within a 1e-5 tolerance with parameter tolerance=1e-5.
VersorRigid3DTransform_SetMatrix raises an error mentioning an epsilon of 1e-10.

**Code**
```
rigid = VersorRigid3DTransform()
rigid.SetMatrix(matrix, tolerance=1e-5)
```

**Exception**
```
Exception has occurred: RuntimeError
Exception thrown in SimpleITK VersorRigid3DTransform_SetMatrix: /tmp/SimpleITK-build/ITK-prefix/include/ITK-5.2/itkVersor.hxx:395:
ITK ERROR: The following matrix does not represent rotation to within an epsion of 1e-10.
0.999088 -0.0276138 0.0325613 
0.0289309 0.998752 -0.0407008 
-0.0313968 0.0416058 0.998641 

det(m * m transpose) is: 0.999999
m * m transpose is:
1 -9.39174e-08 -1.11651e-08
-9.39174e-08 0.999999 5.06677e-08
-1.11651e-08 5.06677e-08 1
```

**Version**
`SimpleITK 2.1.1`

**Comment by zivy** [comment]
Hello @pezize,

This is an issue with ITK (internally using a fixed tolerance, ignoring the user supplied one in this case). I will create an issue for this there, at least open it for discussion. 

To tell the truth I'm not sure the user should have the possibility to specify a tolerance because that opens the door for arbitrary matrices to be provided as "rotation" when they are very far from a rotation. This will cause the internal computations in the class to be erroneous (for example $R^T=R^{-1}$ will no longer be valid). 

A quick workaround is to project the matrix you have onto SO(3) to get the closest rotation matrix in terms of Frobenius norm. See code below:
```
import SimpleITK as sitk
import numpy as np

matrix = [0.999088, -0.0276138, 0.0325613, 
          0.0289309, 0.998752, -0.0407008, 
         -0.0313968, 0.0416058, 0.998641]

rigid = sitk.VersorRigid3DTransform()

try:
    rigid.SetMatrix(matrix, tolerance=1e-5)
except RuntimeError as e:
    M = np.array(matrix).reshape(3,3)
    # Closest rotation matrix in terms of Frobenius norm 
    U, S, Vt = np.linalg.svd(M)
    # U * diag(1,1,det(U*Vt)) * Vt - diagonal matrix ensures that we have a
    # rotation and not a reflection.
    R = U.dot(np.diag((1, 1, np.linalg.det(U.dot(Vt))))).dot(Vt)
    rigid.SetMatrix(R.ravel())

print(rigid)
```

**Comment by pezize** [comment]
Hi @zivy,

Thanks a lot for your answer and the suggested workaround!
I understand your concerns about exposing the tolerance parameter. Removing the tolerance parameter seems a reasonable option to align caller's expectations with ITK internals.

**Comment by zivy** [comment]
Hello @pezize,

You're welcome. Posted this as a [bug on the ITK issue tracker](https://github.com/InsightSoftwareConsortium/ITK/issues/3336), so I'll close this issue here.
