### ISSUE TITLE
Issue with getting numpy array from a view of image differences.

### ISSUE THREAD

**Issue by linako111** [SimpleITK/SimpleITK#1693]
I'm going through the Simple STK learning notebooks.  
There might me a memory leak issue with obtaining slices from images.
In the 03_Image_Details.ipynb notebook in the section with Ellipses (I modified it a bit to show the problem) here is what I get:
![image](https://user-images.githubusercontent.com/29641360/184561646-49311523-ad6d-4ea6-810d-264fe304c3db.png)

**Comment by zivy** [comment]
Hello @linako111,

The issue arises from the usage of `GetArrayViewFromImage` in the code. In the notebook you refer to it says:
"GetArrayViewFromImage(): returns a view on the image data which is useful for display in a memory efficient manner. You cannot modify the data and **the view will be invalid if the original SimpleITK image is deleted**."

The line `adiff2 = sitk.GetArrayViewFromImage(result1 - result2)` is the problem. A temporary SimpleITK image is created to hold the result of image subtraction and a numpy array view is given for that temporary image. Once the image is released (which is up to the Python garbage collector) the view is no longer valid. For example on my mac the code works because the garbage collector didn't delete the temporary SimpleITK image before the numpy computations were done. For stable computation replace:
```
adiff2 = sitk.GetArrayViewFromImage(result1 - result2)
```
with
```
resultdiff = result1 - result2
adiff2 = sitk.GetArrayViewFromImage(resultdiff)
```
or 
```
adiff2 = sitk.GetArrayFromImage(result1 - result2)
```

**Comment by linako111** [comment]
Hello @zivy,

Thanks for the explanation. 
Should the notebook be modified then? 

Thanks!

**Comment by zivy** [comment]
Hello @linako111,

Thanks for the bug report, notebook will be updated once the [pull request ](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/pull/377) passes testing.
