### ISSUE TITLE
ImageRegistrationMethod: different number of iterations per level

### ISSUE THREAD

**Issue by dyollb** [SimpleITK/SimpleITK#1743]
the finer resolution levels can get very slow.

(in the python API) would it be feasible to allow the user to specify different number of iterations per level.
This would make it easier to let the coarse level to fully converge, without exploding execution time in the fine level(s).

I think ANTs allows this.

**Comment by gdevenyi** [comment]
minimum working example you could provide and propose where the change would be in the API?

**Comment by zivy** [comment]
Hello @dyollb,

Two part answer:

# Theory/Philosophy 

Generally speaking, the `numberOfIterations` is the maximal number of iterations. We should have named it `maximalNumberOfIterations` to make this clear. This parameter is a fail-safe, so that the optimization does not continue beyond a certain timepoint. 

The expectation is that the optimization terminate because it satisfies a relevant termination criterion, not max iterations. These convergence criteria have to do with the change in the optimized function value, its magnitude, possibly in the X previous iterations (convergence window). If the termination was due to max iterations, you likely haven't reached the optimum.

Consequentially, as part of the "keep it simple" philosophy of SimpleITK a single max-iterations value is used for all levels of the pyramid. This is a design decision.

# Workaround

You can take full control of the multi-scale registration process by implementing your own multi-scale solution. This is easy to do in SimpleITK and is implemented in [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/66_Registration_Demons.ipynb) under the heading of `multiscale_demons`. You can easily modify the code to repeatedly use a single scale ImageRegistrationMethod with varying settings for each of the levels of the pyramid.

**Comment by dyollb** [comment]
> Hello @dyollb,
> 
> Two part answer:
> 
> # Theory/Philosophy
> Generally speaking, the `numberOfIterations` is the maximal number of iterations. We should have named it `maximalNumberOfIterations` to make this clear. This parameter is a fail-safe, so that the optimization does not continue beyond a certain timepoint.
> 
> The expectation is that the optimization terminate because it satisfies a relevant termination criterion, not max iterations. These convergence criteria have to do with the change in the optimized function value, its magnitude, possibly in the X previous iterations (convergence window). If the termination was due to max iterations, you likely haven't reached the optimum.
> 
> Consequentially, as part of the "keep it simple" philosophy of SimpleITK a single max-iterations value is used for all levels of the pyramid. This is a design decision.
> 
> # Workaround
> You can take full control of the multi-scale registration process by implementing your own multi-scale solution. This is easy to do in SimpleITK and is implemented in [this Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/66_Registration_Demons.ipynb) under the heading of `multiscale_demons`. You can easily modify the code to repeatedly use a single scale ImageRegistrationMethod with varying settings for each of the levels of the pyramid.

Nice. Thanks
