### ISSUE TITLE
SetTransformDomainMeshSize() in voxels or mm

### ISSUE THREAD

**Issue by IlvaHou55** [SimpleITK/SimpleITK#1789]
Hi all,

I am applying a BSpline registration and already have a question during one of the first steps: 

In [this example](https://simpleitk.readthedocs.io/en/v1.2.4/Examples/ImageRegistrationMethodBSpline1/Documentation.html), the following step before registration is performed:

```
transformDomainMeshSize=[8]*moving.GetDimension()
tx = sitk.BSplineTransformInitializer(fixed,
                                      transformDomainMeshSize )
```

In [another example](https://simpleitk.readthedocs.io/en/v1.2.4/Examples/ImageRegistrationMethodBSpline2/Documentation.html), the value of 8 is changed for 10, which made me think twice about this value. 

From [here](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1BSplineTransformInitializerFilter.html#a6728d45d2775534f0cd9c733d6964d26), the following information about this step is available:

_BSplineTransformInitializerFilter is a helper class intended to initialize the control point grid such that it has a physically consistent definition. It sets the transform domain origin, physical dimensions and direction from information obtained from the image. It also sets the mesh size if asked to do so by calling SetTransformDomainMeshSize() before calling InitializeTransform().
SetTransformDomainMeshSize() allows the user to set the mesh size of the transform via the initializer even though the initializer does not do anything with that information. Default = 1^ImageDimension._

Is it correct that the lower this value, the more flexible the deformation? And should this information be given in mm or voxels? And what would be a good choice? Especially since for my application I have an anisotropic voxel dimension (2x2x4 mm). 

Thank you!

**Comment by zivy** [comment]
Hello @IlvaHou55,

Please see answers below.

"Is it correct that the lower this value, the more flexible the deformation? And should this information be given in mm or voxels? And what would be a good choice? Especially since for my application I have an anisotropic voxel dimension (2x2x4 mm)."

No, the larger these numbers the more flexible the deformation. Note that these are multiple numbers, using the Python list replication, so the same expression resolves to [8,8] if a 2D image or [8,8,8] if a 3D image.
This information is unit-less, it literally is the number of control points. The choice depends on the deformation you expect in the physical (mm) world.

For more detailed examples, please see the [BSpline based registration Jupyter notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/65_Registration_FFD.ipynb) and the [Transformations notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/21_Transforms_and_Resampling.ipynb). The [SimpleITK notebooks repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) contains examples that are more detailed, and longer, than the general examples.
