### ISSUE TITLE
Incorrect dicom reading

### ISSUE THREAD

**Issue by lrunaways** [SimpleITK/SimpleITK#1795]
Hello! I found dicom that is not loading properly, though some viewers (Weasis) open it correctly.  I load dicom using:
```
image = sitk.ReadImage(file_path)
image = sitk.GetArrayFromImage(image)[0]
```

![invalid_reading](https://user-images.githubusercontent.com/18750353/208097299-0c8e9b38-21af-4f4b-8ce6-f8b61a8580c4.jpg)

The values of the image seems to be overflown, they lie in range 0...4095. Max value in viewer ~48k.

Some tags:
(0018, 1164) Imager Pixel Spacing                DS: [0.139, 0.139]
(0028, 0002) Samples per Pixel                   US: 1
(0028, 0004) Photometric Interpretation          CS: 'MONOCHROME1'
(0028, 0100) Bits Allocated                      US: 16
(0028, 0101) Bits Stored                         US: 16
(0028, 0102) High Bit                            US: 15
(0028, 0103) Pixel Representation                US: 0
(0028, 1050) Window Center                       DS: '22429.0'
(0028, 1051) Window Width                        DS: '43319.0'
(0028, 1052) Rescale Intercept                   DS: '0.0'
(0028, 1053) Rescale Slope                       DS: '1.0'

Operating system: Ubuntu 18.04.6
Python 3.10
SimpleITK version: 2.2.0 installed through pip
dicom: [invalid_reading.zip](https://github.com/SimpleITK/SimpleITK/files/10245754/invalid_reading.zip)

**Comment by gdevenyi** [comment]
@lrunaways as SimpleITK uses ITK for reading, you should probably upstream this report to https://github.com/InsightSoftwareConsortium/ITK

**Comment by zivy** [comment]
Hello @lrunaways,

Please follow @gdevenyi guidance. Feel free to refer back to this issue or share the information provided below.

From a cursory review, this looks to be an issue possibly in an even deeper layer, GDCM which is used by ITK. It is caused by the conversion from MONOCHROME1 to MONOCHROME2 which ITK does via GDCM which I suspect is causing an overflow (haven't confirmed).

If you read the image via pydicom, which doesn't do the conversion, the original intensity values are retained.
```
import pydicom
import SimpleITK as sitk

ds = pydicom.dcmread("invalid_reading.dcm")
image = sitk.GetImageFromArray(ds.pixel_array)
sitk.Show(image)
```

**Comment by lrunaways** [comment]
Thanks! I'll open an issue in ITK.

Pydicom seems to handle it better, but it also thresholds values to the same range
