### ISSUE TITLE
For Sphinx docs run example and embed output images and text into docs

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#1797]

**Comment by mbopfNIH** [comment]
Working on a solution that uses the Matplotlib.sphinxext.plot_directive sphinx extension. This is used by scikit-image as well as Matplotlib itself to display images in the documentation. May need to build a wrapper script since many of the Examples automatically show the image using Fiji which needs to be turned off via the SITK_NOSHOW environment variable.

**Comment by mbopfNIH** [comment]
**Summary Solution**
The current code uses three different Sphinx extensions to produce output images and text by running the Example python code and Documentation.rst (included in conf.py and requirements.txt):
- `matplotlib.sphinxext.plot_directive`: used to create the plots and make them available to the Sphinx build
- `sphinx_exec_code`: used to run the Python code to include any text output, if desired
- `sphinx_toolbox.collapse`: allows the user to hide long sections of text output by collapsing it

**Code Structure**
- Modified the Example python code to use a standard `def main(args):` routine which is called from within the RST
- Created a helper module, `docs/source/example_utils.py` which contains two functions:
1. `plot_image(image: SimpleITK.Image, cmap: str = 'gray'):` which uses Matplotlib to output a SimpleITK image to make it accessible to Sphinx
2. `run_example(module_name: str, func_name: str, args: list) -> dict:` which encapsulates the standard `main(args)` routine. Since it takes a `func_name`, using "main" is just a convention, and the code will accept other names.

The above routines are called from within the RST file for each example using the code section of the ..plot:: directive as so:
`.. plot::
   :align: center
   :nofigs:

    import os
    import sys

    from example_utils import run_example, plot_image
    args = [arg1, arg2, arg3...]
    
    return_dict = run_example(<ExampleName>, 'main', args)
    for key, value in return_dict.items():
        plot_image(value)`

Note that the run_example expects the main routine to return a `dict[str, SimpleITK.Image]` which is iterated through and all desired images displayed using the `plot_image` routine.
Also note that the `:nofigs:` option is usually included in the plot directive to avoid directly including the images in the output. This is done to provide more control over the display of the images, such as:
`.. list-table::

    * - .. figure:: link_ImageRegistrationMethod1_docs-1_00.png
           :scale: 100%

           **Fixed Image**

      - .. figure:: link_ImageRegistrationMethod1_docs-1_01.png
           :scale: 100%

           **Moving Image**`

**Issues**
- The current filenames referenced in the RST files are based on the plot directive's naming convention. These images are not available during the initial stages of the processing, so they produce warning messages. This is a fragile approach and should be revisited.
- There maybe be a cleaner way to access these images. The also reside in a directory called "plot_directive" under the "build" directory. There should be a way to tell the Sphinx build to look in that directory at creation time.
- The sphinx_code_exec recently upgraded from version 0.8 to 0.9 and broke our build, possibly due to an interaction with the sphinx_toolbox.collapse extension.

**Continuing work**
- Creating a custom Sphinx extension of our own could have a lot of advantages. We could either attempt to extend the plot_directive or code_exec extensions, or use the concepts as a starting point. Both have a reasonably large code base with which to work.
- Modifying the `def main(args)` function to use **kwargs would allow for easier handling of the different command line arguments, especially for those Examples with numerous options.
- There are, of course, many additional Examples to also add images and text output to.

**Comment by mbopfNIH** [comment]
Here is a list of related sub-issues:
#1798 
#1831

**Comment by zivy** [comment]
Thanks for the contribution.
