### ISSUE TITLE
Embed the output of DicomImagePrintTags in Sphinx

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#1798]
This example only contains text output and is a good starter where the existing Sphinx extensions doctest or other extension should work.
Part of #1797

**Comment by mbopfNIH** [comment]
Having difficulty finding a good Sphinx extension for running the Example code. I thought [sphinx-exec-code](https://sphinx-exec-code.readthedocs.io/en/latest/index.html) would work, but it doesn't allow me to reference a subset of the Example code file.

**Comment by mbopfNIH** [comment]
I now have sphinx-exec-code is now running, but requires a DICOM image as input, and I don't see any in the "docs/images" path in the sphinx build - it's all jpg, png, and svg. Will look into how to get on in there and find an appropriate image.

**Comment by zivy** [comment]
Hi @mbopfNIH, 

Possibly use the files that are referenced in the testing of the examples which use DICOM (e.g. [DicomConvert](https://github.com/SimpleITK/SimpleITK/blob/master/Examples/DicomConvert/CMakeLists.txt)). These are images that are already in the binary data store, see their hash files under the [Testing/Data/Input](https://github.com/SimpleITK/SimpleITK/tree/master/Testing/Data/Input/DicomSeries) directory. 

If they are not visually compelling, you may need to add several DICOM images to the binary data store under the docs/images path.

**Comment by mbopfNIH** [comment]
Thanks, Ziv. I’m trying to understand the make/cmake build process and how the CMake ExternalData module knows where our images are stored. A make -debug shows that they are coming from an AWS s3 bucket, but I can’t see where that is set – I suspect some “magic” is going on (which magic defined as anything I don’t understand).

In any case, I’ll take a look at the 3 DICOMs I can find in Testing/Data/Input.

From: Ziv Yaniv ***@***.***>
Date: Tuesday, December 27, 2022 at 10:50 AM
To: SimpleITK/SimpleITK ***@***.***>
Cc: Bopf, Mike (NIH/NIAID) [C] ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [SimpleITK/SimpleITK] Embed the output of DicomImagePrintTags in Sphinx (Issue #1798)

Hi @mbopfNIH<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FmbopfNIH&data=05%7C01%7Cmbopf%40mail.nih.gov%7Cab3dfb77d54e4611cda308dae8220a2a%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638077530144377370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KtMpylS8MPmzQoiYIk99Nn5toPSSHkmNTsPlicVsfY0%3D&reserved=0>,

Possibly use the files that are referenced in the testing of the examples which use DICOM (e.g. DicomConvert<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSimpleITK%2FSimpleITK%2Fblob%2Fmaster%2FExamples%2FDicomConvert%2FCMakeLists.txt&data=05%7C01%7Cmbopf%40mail.nih.gov%7Cab3dfb77d54e4611cda308dae8220a2a%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638077530144377370%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=50gBawH%2FiwRjIjs%2Bq2GDu6YpFpUYfUCNQiQjYpYuqrs%3D&reserved=0>). These are images that are already in the binary data store, see their hash files under the Testing/Data/Input<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSimpleITK%2FSimpleITK%2Ftree%2Fmaster%2FTesting%2FData%2FInput%2FDicomSeries&data=05%7C01%7Cmbopf%40mail.nih.gov%7Cab3dfb77d54e4611cda308dae8220a2a%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638077530144533557%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vWqYhP9stJJR99xsxl2gIXjCjyIiywpet286x%2FkpZYQ%3D&reserved=0> directory.

If they are not visually compelling, you may need to add several DICOM images to the binary data store under the docs/images path.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSimpleITK%2FSimpleITK%2Fissues%2F1798%23issuecomment-1366003196&data=05%7C01%7Cmbopf%40mail.nih.gov%7Cab3dfb77d54e4611cda308dae8220a2a%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638077530144533557%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=P2%2FzngeTiTkeE2d9J3evObf4fJJ2tQgBCjYF%2FOuZQSk%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJJH232XKVWHGI4ODKKMYALWPMF27ANCNFSM6AAAAAATBOSXNQ&data=05%7C01%7Cmbopf%40mail.nih.gov%7Cab3dfb77d54e4611cda308dae8220a2a%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638077530144533557%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EqQI6re4CDawmr9dp9vX4chMj6UP8lt%2Bjc%2B%2FpJDScmw%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by zivy** [comment]
The location of the images is explicitly given [here](https://github.com/SimpleITK/SimpleITK/blob/aff11ddc90bde4cc1669bb54a60dec52d50c0507/CMake/sitkExternalData.cmake#L39). The algo is "md5" or "sha512" and the hash is just the image hash.

**Comment by mbopfNIH** [comment]
I have a "solution" for this text-only case:
- Added the sphinx_exec_code directive to the docs/requirements.txt and conf.py
- Copied Image0075.dcm.sha512 from Testing/Data/Input to docs/images, although almost any DICOM image would work
- Modified DicomImagePrintTags/Documentation.rst to run DicomImagePrintTags.py as a subprocess, since it is a script, passing it Image0075.dcm as input.

I will create a PR
