### ISSUE TITLE
Reformat Output in Sphinx

### ISSUE THREAD

**Issue by blowekamp** [SimpleITK/SimpleITK#1831]
The the Sphinx example the output/input should be before the sample code. Output could be an image or text.

Also images should be centered.

**Comment by mbopfNIH** [comment]
One issue: if there’s a LOT of output (like the DicomPrintTags Example), the code will appear waaaay down on the page. Vertical scrollbars would be a possibility, but I have no idea how I might accomplish that.

From: Bradley Lowekamp ***@***.***>
Date: Thursday, January 19, 2023 at 1:33 PM
To: SimpleITK/SimpleITK ***@***.***>
Cc: Bopf, Mike (NIH/NIAID) [C] ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] [SimpleITK/SimpleITK] Reformat Output in Sphinx (Issue #1831)

The the Sphinx example the output/input should be before the sample code. Output could be an image or text.

Also images should be centered.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSimpleITK%2FSimpleITK%2Fissues%2F1831&data=05%7C01%7Cmbopf%40mail.nih.gov%7C8ef2300b732c4464b50308dafa4ba485%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638097500027175951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b43LeyvPR5hduwwt9P7wdCj9bhuwWFWm%2BeiwpcaSBd4%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJJH236EOGN4C567GLRGEDLWTGCGFANCNFSM6AAAAAAUAVMIHE&data=05%7C01%7Cmbopf%40mail.nih.gov%7C8ef2300b732c4464b50308dafa4ba485%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638097500027175951%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sedSmuQmeDSnofRJ3FV%2B%2BuAwDSyOYsqkPbAPePdHfKE%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by zivy** [comment]
Possibly consider looking into [this extension](https://sphinxcontrib-programoutput.readthedocs.io/en/latest/) which supports shortening of output via ellipsis. Haven't gone beyond reading the overview, so don't know if this is useful or not.
