### ISSUE TITLE
Is it possible to publish SimpleITK with Elastix included?

### ISSUE THREAD

**Issue by aiq-kgielow** [SimpleITK/SimpleITK#1895]
According to the release notes for v.2.2.0, it looks like Elastix filters can be included if compiled with a special flag.  This is fantastic and I'd love to use it so we can upgrade to Python 3.10.  However, this flag is disabled by default.

Is it possible to compile and publish a package to PyPI that does include the Elastix filters?

**Comment by zivy** [comment]
We currently do not have plans to compile and publish the package to PyPI as it is not as stable like the rest of SimpleITK (e.g. [this issue](https://github.com/SimpleITK/SimpleITK/issues/1891)). 

For now, please [build it for your platform](https://simpleitk.readthedocs.io/en/master/building.html) by turning the `SimpleITK_USE_ELASTIX` flag on.

**Comment by yoda-vid** [comment]
I've been building SimpleITK with Elastix for use as a dependency in the MagellanMapper package. We build wheels for Python 3.8-3.11 (macOS (Intel), Windows, Linux), though on an ad hoc basis since they're built using a local computer. I'm currently hosting them on a third-party PyPI server, but would there be any utility in hosting them on the main PyPI as a separate package? Or other hosting options?
