### ISSUE TITLE
Cannot build SimpleITK on windows - git download fails

### ISSUE THREAD

**Issue by DrDryg** [SimpleITK/SimpleITK#1903]
I try to build SimpleElastix for c#. But it fails to download something from Git. I dont have any issue with my internet connection. I have installed git on the computer and it works fine. I have win 11, vs community 2022.
 
Build started...
1>------ Build started: Project: SuperBuildSimpleITKSourceReal, Configuration: Release x64 ------
2>------ Build started: Project: ITK, Configuration: Release x64 ------
2>1>Performing download step (git clone) for 'ITK'
1>1>
3>------ Build started: Project: Swig, Configuration: Release x64 ------
4>------ Build started: Project: Lua, Configuration: Release x64 ------
3>1>
4>1>
2>Cloning into 'ITK'...
2>fatal: unable to connect to github.com:
2>github.com[0: 140.82.121.3]: errno=Unknown error

**Comment by DrDryg** [comment]
Found an answer here: https://stackoverflow.com/questions/72486457/fatal-unable-to-connect-to-github-com-github-com0-140-82-121-4-errno-unkno

In case someone else run into the issue.

**Comment by blowekamp** [comment]
I presume from the linked SO that the following git configuration change was applied: `git config --global url.https://github.com/.insteadOf git://github.com/`

However, this should not currently be needed. This is likely related to [Github dropping the `git`](https://github.blog/2021-09-01-improving-git-protocol-security-github/) protocol in favor of use the secured https.

Can you please check the `SimpleITK_GIT_PROTOCOL` variable in the Superbuild CMake configuration is should be "https"?

Perhaps your git version was incorrectly detected and [the protocol was set to `git`](https://github.com/SimpleITK/SimpleITK/blob/master/SuperBuild/SuperBuild.cmake#L118). That logic there should be updated since the git protocol no longer works.

Thank you for reporting the issue, if there is an underlying automatic configuration issue in SimpleITK it would be good to address it so others do not need this work around.

**Comment by DrDryg** [comment]
Indeed looks like the https has been dropped
![image](https://user-images.githubusercontent.com/36692294/223724722-6846efd6-80a7-4440-b3cf-f05ac4fd5d32.png)
