### ISSUE TITLE
B-Spline Interpolation order 0

### ISSUE THREAD

**Issue by kmalhotra30** [SimpleITK/SimpleITK#1910]
B-Spline interpolation supports orders from 0 to 5, however only 1 to 5 are present in the interpolator enum here : https://github.com/SimpleITK/SimpleITK/blob/36c0ed9512bb5141c6e7d85bf1bb68d31191c3a5/Code/Common/include/sitkInterpolator.h#L30

How to go about using B-spline interpolation with order 0?

**Comment by zivy** [comment]
Hello @kmalhotra30,

Order zero in the underlying ITK implementation is equivalent to nearest neighbor (see [code here](https://github.com/InsightSoftwareConsortium/ITK/blob/379eb109e99728e5b7f97fce35a6ab05a6571de6/Modules/Core/ImageFunction/include/itkBSplineInterpolateImageFunction.hxx#L181-L202)). In SimpleITK just use `sitk.NearestNeighbor` instead of a BSpline of order 0.

**Comment by kmalhotra30** [comment]
Alright, thanks for the help.

**Comment by kmalhotra30** [comment]
Sorry to re-open the issue @zivy , in general spline order 0 is not the same as nearest neighbor ? or in ITK the implementation is same?

**Comment by zivy** [comment]
Hello @kmalhotra30,

Generally speaking, you are correct, spline order zero is not the same as nearest neighbor, but in ITK it appears to be that order zero is nearest neighbor, at least according to the documentation. From a practical standpoint, what matters is the implementation, as the theory is on paper and does not necessarily match what was implemented.

**Comment by kmalhotra30** [comment]
@zivy I see,  thanks for your response.
