### ISSUE TITLE
Reading images in Google Cloud

### ISSUE THREAD

**Issue by sbonaretti** [SimpleITK/SimpleITK#1918]
Hi! 

Not sure this is the right place, but I will give it a try. 

I am trying to read an image located in Google Storage from a notebook running in Vertex AI, but I get ` The file "gs://<bucket_name>/<image_name.mha>" does not exist`. I can read other kinds of files located in the same folder (e.g. `.csv` using pandas) and I tested that the file exists.

Do I need to set up something specific for SimpleITK? 

Thank you very much for your kind help!

**Comment by zivy** [comment]
Hello @sbonaretti,

Well, the google cloud storage isn't a local file system and SimpleITK can only read from a local or mounted directory.
You can mount the gcs, as [described here](https://jerrizhang.medium.com/how-to-mount-a-gcp-bucket-in-google-colab-febe12d9839a).

Less recommended, but if for some unknown reason your really don't want to mount the gcs, you will need to explicitly download the file from and then read it:
```
!gsutil cp gs://{bucket_name}/image_name.mha /tmp/x.mha

image = sitk.ReadImage("/tmp/x.mha")
```
This is similar to the [fetch_data](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/3ccfe9dbca2c91280ee4d719c654f630625e4ad2/Utilities/downloaddata.py#L260) method used in the SimpleITK notebooks repository (fetch data also uses local caching, so slightly smarter than downloading every time). That is why in the [notebooks repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) image reading looks like:
```
image = sitk.ReadImage(fdata(image_file_name))
```
instead of
```
image = sitk.ReadImage(image_file_name)
```

**Comment by sbonaretti** [comment]
Hi @zivy,
Thanks so much for telling me the basics and pointing me towards the right direction! 
At the end, I followed [this video](https://www.youtube.com/watch?v=tnhX93pFFz0&t=1292s) (starting from min. 15:20), in case it can be helpful for somebody else! The blog is for Google Colab, but I am using Jupyter notebook!
