### ISSUE TITLE
Documentation improvement request

### ISSUE THREAD

**Issue by chsasank** [SimpleITK/SimpleITK#220]
Hi!

I see that you're moving the documentation to readthedocs! Great!

IMHO, 'getting started' is too long for a new user to get started on using SimpleITK? I can understand that having it is useful for old users and therefore you want to keep it. New user will be overwhelmed by amount of information in this page. I think renaming the title of this page to something else helps.

I think, a "Getting Started" should have a very concise version of installation (like [this one](http://simpleitk-prototype.readthedocs.io/en/latest/installation.html)) and few code snippets which describe core functionality of the library.

Sasank.

**Comment by rohitghosh** [comment]
I completely agree that the amount of information currently mentioned in readthedocs is overwhelming, to say the least. Just to get started, a simple and followable instruction should be enough. Something like 
`pip install simpleitk` just should do.

**Comment by zivy** [comment]
@chsasank,
First of all, we really appreciate the prototype sphinx documentation you provided, this is what convinced us to move to a sphinx+readthedocs documentation approach.

@chsasank, @rohitghosh, 
The current version on readthedocs is a work in progress, initial porting of all the information we have on the wiki. 

With regard to install+build, we agree with both of you and will separate the installation instructions from the build instructions. 

Note though that our installation page will never be as simple as a single command, just due to the fact that SimpleITK supports 8 programming languages. Each of these will have its own installation method. Not to mention that even in the Python community you will either use pip or conda based on your distribution. Also, for some of the languages we currently do not have binary distributions so their installation instructions will also need to point to the build instructions (on a separate page). 

Hopefully this clarifies some of our design decisions.

**Comment by blowekamp** [comment]
Please see the split "installation" page here:
http://simpleitk.readthedocs.io/en/next/Documentation/docs/source/installation.html
