### ISSUE TITLE
Running out of system memory due to repeated WriteImage

### ISSUE THREAD

**Issue by beaslera** [SimpleITK/SimpleITK#2206]
**Describe the bug**
Calling WriteImage repeatedly uses increasing amounts of system memory until the program crashes.

**To Reproduce**

1. Operating system, version, and architecture
 - OS: Ubuntu 20.04
 - Architecture: Intel Broadwell
2. Programming language, and version
Python 3.11.3 (main, Jun 29 2023, 13:17:53) [GCC 11.3.0] on linux
4. Version of SimpleITK [e.g. 1.1.0], output of the SimpleITK Version() function.
SimpleITK Version: 2.4.0 (ITK 5.4)
Compiled: Aug 13 2024 14:08:24
5. How was SimpleITK installed?
binary distribution via `python -m pip install simpleitk`
6. A minimal working example which causes the error.
This script runs out of system memory (64GB) and crashes trying to save the 209th image.
```
import SimpleITK as sitk


def sitk_write_image():
    """Repeatedly call WriteImage."""
    image = sitk.Image(300, 512, 512, sitk.sitkFloat32)
    for i in range(1000):
        output = f"image-{i}.nrrd"
        print(f"Saving to {output}")
        sitk.WriteImage(image, output)


if __name__ == "__main__":
    sitk_write_image()
```

**Expected behavior**
Memory use should stabilize so the program does not crash.

**Additional context**
- The crashes are occurring on a Google Cloud Platform VM.
- The same script does not crash in another environment: not on GCP, no VM, running Windows Subsystem for Linux. Instead, the in-use memory reported by Task Manager grows linearly until it stabilizes around 49GB out of the 64GB available.
- I am seeing this behavior across various images and file formats.

**Comment by zivy** [comment]
Hello @beaslera,

Not sure why this would occur. I tried replicating on OSX and memory usage does not change during the execution. 

I tried the specified versions via a GitHub actions runner (had to reduce the number of iterations to 40 so that didn't run out of disk space ~300MB for file). From the [telemetry on that PR](https://github.com/zivy/code_test/pull/1) it doesn't seem that the memory usage changes.

Guesstimating here, could this be somehow an issue with running out of disk space on the GCP VM and that leads to some arbitrary error message? For the 1000 files this is ~300GB.

As a side note, the `WriteImage` has a `useCompression` flag (`sitk.WriteImage(image, output, True)`). Turning it on for the existing code reduces the file size from 300MB to ~300K.

**Comment by beaslera** [comment]
Thank you both for looking at this.  I appreciate your responsiveness.
I've been continuing to work on it and I think what's happening is that the environment is using tempfs and I have been working in the tmp folder.  Saving the files somewhere else does not result in the memory usage growing.
