### ISSUE TITLE
The memory shared between numpy and itk, and ask for help about ImagePy

### ISSUE THREAD

**Issue by yxdragon** [SimpleITK/SimpleITK#231]
I am building a image process framework ImagePy, If you know ImageJ, then ImagePy is ImageJ(Python) but more simpler and pythonic, which based on plugin, and generate friendly interaction. what more, ImagePy is based on Numpy, that meas we can glue with scipy, scikit-image, opencv directly!

Now, I want to write plugin set wrap simpleITK, then not only programer, but no-programer, doctor and biologist could use itk! but... I find I must use imagefromarray, arrayfromimage to copy between numpy and simpleitk ... Is there any direct way (shared memery)?

by the way. Is there any one intrested in [ImagePy](https://github.com/Image-Py/imagepy), the framework is basicly ok! just write plugins, you are welcom, I need help!

**Comment by zivy** [comment]
In release 1.0.0 we added a shared memory read only buffer using the function GetArrayViewFromImage . You can use this buffer as input to your numpy based image analysis filters as long as they don't need to write back into it. 

With regard to creating a SimpleITK image from a numpy array we copy the memory so that we can maintain our internal data structures (underlying ITK image...).

**Comment by blowekamp** [comment]
The question appears addressed. Feel free to re-open if needed or ask another question.
