### ISSUE TITLE
Problem with RelabelComponentImageFilter

### ISSUE THREAD

**Issue by lilipj** [SimpleITK/SimpleITK#304]
Hello,

I'm using ITK, and since a few days SimpleITK, and I've got a problem with the RelabelComponentImageFilter.
I haven't found the way to change the minimum objects size, here is my code (SimpleITK via Java) :

BigInteger islet_size = BigInteger.valueOf(round(height/5)); // = 102
RelabelComponentImageFilter relabelFilter = new RelabelComponentImageFilter();
relabelFilter.setMinimumObjectSize(islet_size);
BigInteger taille = relabelFilter.getMinimumObjectSize();
System.out.println(taille);
relabelImage[i] = relabelFilter.execute(connectedComponentOutput[i]/*, islet_size*/);

The size displayed in the terminal  is :  class org.itk.simple.SimpleITKJNI

and the output image is filled full black.
I've added a MinimumMaximumImageFilter, and it confirms that min = 0.0 and
max = 0.0
and when i run a LabelStatisticsImageFilter, it seems to return 0 label
stat.hasLabel(0) = 1.0
stat.hasLabel(1) = 0.0

if i don't set the minimum size, it returns 207 objects...

I don't understand the problem.

Thanks in advance.

**Comment by blowekamp** [comment]
Thank you for reporting your issue here. One suggestion was:

>

> From: Dženan Zukić 
> Date: Thursday, September 28, 2017 at 9:37 AM
> 
> Also, after you call execute, can you call relabelFilter.GetOriginalNumberOfObjects() and see if this returns non-zero number?

I have added the missing functions to SimpleITK in #303. These new features are currently available in the master branch. You will need to compile SimpleITK for the git repository to use these new features.

Regarding this particular problem. I would look at the statistics computed by the `LabelStatisticsImageFilter` for your label image, before and after running the `RelabelComponentImageFilter` with different options. With the statistics filter you can look at the labels and determine their sizes to know how many should remain.

**Comment by addisonElliott** [comment]
What is the status of this issue? Was it fixed by #303? Can this be closed now?

**Comment by blowekamp** [comment]
I am closing the issue, the #303 added some missing functions to the filter that were encountered while debugging the issue. I presume the original report has discovered his problem or worked around it by now. Reopen if needed.
