### ISSUE TITLE
Using simple ITK ReadImage function under win10

### ISSUE THREAD

**Issue by Meresmata** [SimpleITK/SimpleITK#454]
Hi,

 I am trying to open MRI documents  (.raw/.mhd) with simpleITK under win10(import) (64-bit) and  Ubuntu-derivate (64-bit). I tried different SimpleITK versions on Python 3.6 and 3.5(mainly). I installed them with conda and also use conda to create a virtual environment. When I want to open the MRIs with ReadImage, I always get the error message, that the file does not exists. But I tested existence and reading rights beforehand. Hence, if the file did nor exists, the ReadImage function would not be called.

I do not get the error on the Linux machine. In fact, all is working perfectly there. But windows functional is vital for me. I hope, that we can work that out!

**Comment by zivy** [comment]
To effectively help you with the problem we need more details with respect to the error (please cut and paste the complete error message). 

Given that you only encountered the issue on windows it could be something with the path to the file, I am guessing here:
1. path length too long.
2. non ascii characters in path
3. spaces in the path
...

Please provide more information or let us know if your issue is resolved.

**Comment by Meresmata** [comment]
Thanks. That hint helped a lot!

I tested a bit on. It was the problem with the non ascii characters. Spaces have been "accepted".
