### ISSUE TITLE
invoke Fiji repeatly

### ISSUE THREAD

**Issue by JianJuly** [SimpleITK/SimpleITK#470]
SimpleITK always invoke Fiji when i use Show( ) function, even if i have already opened a Fiji window. That makes it slow when i want to show an image.

**Comment by zivy** [comment]
This is primarily a Fiji issue. A discussion on how to configure Fiji to use a single instance can be found [here](http://imagej.1557.x6.nabble.com/Run-Single-Instance-Listener-option-disappeared-td5016173.html).

If this resolves the problem, please close the issue, otherwise please provide additional details (SimpleITK version, OS, Fiji version...) so that we can better help you.
