### ISSUE TITLE
error: can't copy 'F:\Buildsimpleelastix\SimpleITK-build\Wrapping\Python\_SimpleITK.pyd': doesn't exist or not a regular file

### ISSUE THREAD

**Issue by fitushar** [SimpleITK/SimpleITK#535]

**Comment by zivy** [comment]
From the error message this appears to be a SimpleElastix issue. That is a toolkit built on top of SimpleITK. You can post the issue on [their issue tracker](https://github.com/SuperElastix/SimpleElastix/issues). I would also recommend providing details beyond the error message, otherwise it is all but impossible to help.
