### ISSUE TITLE
Python SimpleITK.image equals instead of broadcast

### ISSUE THREAD

**Issue by Styp** [SimpleITK/SimpleITK#583]
I couldn't find anything in the API documentation but is there a SimpleITK.Image equal on object level? I just want to know if two objects are the same. In numpy this exists by design np.equals()

Thanks!

**Comment by blowekamp** [comment]
Any comparison operator on the image should be for the object not the data. There are filters for a variety of different image data comparisons. He is the doxygen for the  Equal filter:

https://itk.org/SimpleITKDoxygen/html/sitkEqualImageFilter_8h.html

On Oct 17, 2018, at 7:52 AM, Martin Stypinski <notifications@github.com<mailto:notifications@github.com>> wrote:


I couldn't find anything in the API documentation but is there a SimpleITK.Image equal on object level? I just want to know if two objects are the same. In numpy this exists by design np.equals()

Thanks!

**Comment by Styp** [comment]
That is impossible, because of:

```
class Foo:
    pass

def test_foo_class():
    X = Foo()
    Y = Foo()

    assert X == Y

def test_itk_class():
    X = sitk.Image(10, 10, 10, sitk.sitkFloat32)
    Y = sitk.Image(10, 10, 10, sitk.sitkFloat32)
    
    assert X == Y
```

The assert fails with Foo() but does not fail with sitk.Image(). Which leads to the conclusion that the '==' is returning a new object instead of a boolean type.
Further: http://simpleitk.github.io/SimpleITK-Notebooks/02_Pythonic_Image.

Or am I completely wrong?

**Comment by blowekamp** [comment]
I was just thinking of and looking at the C++ interface. For the Python interface your code is correct. The comparison operators are [overloaded](https://github.com/SimpleITK/SimpleITK/blob/master/Wrapping/Python/Python.i#L228-L271) with the filters I pointed to.

If you would like to know if they are the sample Python object you could do `id(X) == id(Y)`. To complicate things SimpleITK does lazy coping with copy on write. So while `Y = sitk.Image(Y); id(X) != id(Y)` if you print X and Y you'll see they still point to the same buffer.

Hope that help you understand things better. If you have a specific questions about how to do something please ask.
