### ISSUE TITLE
Clarify ITK build dependencies and intro doc.

### ISSUE THREAD

**Issue by phcerdan** [SimpleITK/SimpleITK#61]
Hey, I am about to contribute to ITK with a new module (ITKIsotropicWavelet). I shouldn't worry about SimpleITK at this stage, but using `sitk` in python in just so awesome for fast prototyping, that I want to help with the integration of the module into SimpleITK, and also learn more about swig and wrapping c++.

I am not really sure reading this intro:
[http://www.simpleitk.org/SimpleITK/project/about.html](http://www.simpleitk.org/SimpleITK/project/about.html) about the differences between ITKWrap facilities (from ITK)  and SimpleITK.

Also your recommendation about doing a superbuild of SimpleITK doesn't help to know more about what do you need from ITK. I am sure the information is there if I read the CMake files here in github, but a little bit of a intro/explanation would be really appreciated.

Thanks!

**Comment by blowekamp** [comment]
Hi, I am glad to hear you find using SimpleITK useful and fast. The About page is maintained by Kitware and provides some basic general information. You can find more detailed and up to date info on the Community maintained Wiki (https://itk.org/Wiki/SimpleITK). Contributions to clarify are welcomed.

You are correct in that the full configuration options needed for ITK are in the repository (https://github.com/SimpleITK/SimpleITK/blob/master/SuperBuild/External_ITK.cmake) and there is some info on the wiki (https://itk.org/Wiki/SimpleITK/GettingStarted#Building_manually). When you configure SimpleITK/SuperBuild you can set USE_SYSTEM_ITK:BOOL=ON and ITK_DIR=your_itk_dir, so that you can use your local custom copy of ITK. It is not a bad idea to learn a little bit of how SimpleITK does it wrapping to guide the interface design of your ITK Module.

Regarding SimpleITK vs WrapITK ( native python ITK ): WrapITK looks like this (https://itk.org/ITKExamples/src/Filtering/Smoothing/SmoothWithRecursiveGaussian/Documentation.html) while SimpleITK looks like this (https://itk.org/SimpleITKDoxygen/html/Python_2SimpleGaussianProcedural_8py-example.html) or this (https://itk.org/SimpleITKDoxygen/html/Python_2SimpleGaussian_8py-example.html). Native Python ITK provides only a Python interface to the templated pipelined C++ interface of ITK, while SimpleITK provides a template free wrapping with an optional procedural interface for many languages for most of ITK's ImageFilters and an interface to the registration framework.

Also note that we are planning on improving the ITK modularity of SimpleITK for the next release to enable SimpleITK to respect the modules enabled in ITK.

HTH
