### ISSUE TITLE
Feature request - Please add OrientImageFilter 

### ISSUE THREAD

**Issue by John1231983** [SimpleITK/SimpleITK#644]
I want to reorient the nii image to some direction such as RAI. It can work in itk, but simple-itk does not have the filter. Could you consider to integrate it in simple-itk?

This is some script itk code
```
using FilterType = itk::OrientImageFilter< InputImageType, OutputImageType>;
orientation_filter->SetDesiredCoordinateOrientation( itk::SpatialOrientation::ValidCoordinateOrientationFlags::ITK_COORDINATE_ORIENTATION_RAI);
orientation_filter->UseImageDirectionOn();
```

**Comment by blowekamp** [comment]
That is a good suggestion! Thanks!

**Comment by John1231983** [comment]
@blowekamp: careful using the above API. Although I call the API to reorientation from LPI to RAI, but when I open in ITK, it still shows `Oblique (closest to RAI)`

**Comment by sbonaretti** [comment]
Hi! I need this filter too! I have my own python implementation using ITK, but it seems to work only on some machines (no idea why)! I have seen that the issue is closed. When are you going to make this filter available? Thanks so much!!!

**Comment by blowekamp** [comment]
This issue is open and scheduled for the 1.3 release.

**Comment by sbonaretti** [comment]
That's great! Thanks!!! Do you have any idea about the timeline?

**Comment by blowekamp** [comment]
The PR is here: #798

Unfortunately the output names spaces do NOT match that of the DICOM standard in ITK. This would create too much confusion in its usage. I think ITK needs a new orient filter which follows the DICOM standard for names spaces.

InsightSoftwareConsortium/ITK#1163

**Comment by gdevenyi** [comment]
Definitely +1 this here. Such a feature is essential if writing code where you always want to iterate along an image in the same anatomical direction and can't guarantee the on-disk orientations. Right now we use nibabel's as_closest_canonical to handle this, but we'd like to drop it as a dependency to just use SimpleITK

**Comment by blowekamp** [comment]
Just to be clear, are you expecting the image to be resampled such that cosine matrix exactly matches the anatomical orientations ( i.e. the matrix is composed of 1, -1, 0 )? Or that the image is flipped, and axis ordered so that the anatomical orientations are the closes to the principle axis?

Understanding orientation can getting every thing consistent is challenging. The mismatch of names in the itk OrientImageFilter adds to the confusion. I am reimplemented the filter calling it DICOMOrientImageFilter here: https://github.com/SimpleITK/ITKSimpleITKFilters/pull/24/files#diff-4030c951de5e817f7fb4bf8e6ffd08d0

It needs more testing, contributions are welcomed. It could make it into SimpleITK 2.0 with a bit of nudging. You comments are appreciated.

**Comment by gdevenyi** [comment]
> Just to be clear, are you expecting the image to be resampled such that cosine matrix exactly matches the anatomical orientations ( i.e. the matrix is composed of 1, -1, 0 )? Or that the image is flipped, and axis ordered so that the anatomical orientations are the closes to the principle axis?

I want exactly what DICOMOrientImageFilter does, thanks for the link. I want to pass the image through a filter so that I can assume that iteration over +X will give be +R, for example in an RAS.

I'll take a look at the filter and kick the tires.

**Comment by blowekamp** [comment]
@gdevenyi The DICOMOrientImageFilter is available in the latest/nightly binary releases:
https://github.com/SimpleITK/SimpleITK/releases/tag/latest

There is a minor valgrind defect being addressed, but it should not effect basic operations.

**Comment by makquel** [comment]
Is there any way to use this filter for NifTI format?

**Comment by makquel** [comment]
Is there any rotation/orientation filter that I could use to reorient or rotate to the proper radiological orientation? The followinf is an example of what I'm trying to achieve, since the original NIfTI comes as a sagittal view,
![Captura de tela de 2020-12-03 07-46-33](https://user-images.githubusercontent.com/1332029/101011116-41eb0600-3541-11eb-84aa-dcf055a9ee85.png)

**Comment by blowekamp** [comment]
The resolution of this issue was to create and wrap the [DICOMOrientImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1DICOMOrientImageFilter.html). If that filter does not meet you needs place please create a new issue for you specific case.
