### ISSUE TITLE
WarpImageFilter and Image sizes

### ISSUE THREAD

**Issue by aschmiri** [SimpleITK/SimpleITK#702]
I'd like to use the WarpImageFilter to warp a (moving) image to the domain of a reference image after registration. However, I get

sitk::ERROR: Both images for WarpImageFilter don't match type or dimension!

as moving image and displacement field do not have  the same size (which is totally reasonable in case of image registration). I think this is caused because the sitkDualImageFilterTemplate is used. However, in my opinion, this constraint doesn't really makes sense in the case of image warping.

**Comment by blowekamp** [comment]
Please provide minimal code to demonstrate your usage so that the error can be reproduced. I think you are correct here, also the error message is not indicative of the actual check done in sitkWarpImageFilter.cxx. However, we will also need to check to see of the underlying ITK filter behaves. I have only used this filter with Demons registration, when the size of moving and the displacement field are the same.

Also please note, that the ResampleImageFilter can be used to perform warping too. The DisplacementField image just needs to be converted into a DisplacementFieldTransform.

**Comment by aschmiri** [comment]
A pretty dump synthetic example would be

```
moving = sitk.GetImageFromArray(np.ones((20, 20, 20)))
moving.SetSpacing((1.0, 1.0, 1.0))

displacement = sitk.GetImageFromArray(np.zeros((10, 10, 10, 3)), isVector=True)
displacement.SetSpacing((2.0, 2.0, 2.0))

warped = sitk.Warp(moving, displacement)
```

Note that I chose the same domain for moving image and displacements (just different spacings/sizes), which should not even be necessary. Principally, moving, reference and displacement geometry can differ.

I've tested warping with the ResampleImageFilter, this works:

```
resampler = sitk.ResampleImageFilter()
resampler.SetReferenceImage(displacement)
resampler.SetTransform(sitk.DisplacementFieldTransform(
    sitk.Cast(displacement, sitk.sitkVectorFloat64)))
warped = resampler.Execute(moving)
```

**Comment by blowekamp** [comment]
Thank you for the sample code to clearly illustrate the issue.
