### ISSUE TITLE
sitk::ERROR: No appropriate executable found

### ISSUE THREAD

**Issue by rojinsafavi** [SimpleITK/SimpleITK#723]
I am having the same issue

I have fiji installed on my MAC (The one that has user interface and you can load and look at the images) 

I ran following code from your examples:

python ImageRegistrationMethod1.py ~/Downloads/chrome_dl/k/C2-Composite0.tif ~/Downloads/chrome_dl/k/C2-Composite1.tif trial.hdf5

and I got:

Optimizer stop condition: RegularStepGradientDescentOptimizerv4: Step too small after 18 iterations. Current step (0.0078125) is less than minimum step (0.01). Iteration: 19 Metric value: 24522.5579727 Traceback (most recent call last): File "ImageRegistrationMethod1.py", line 71, in <module> sitk.Show( cimg, "ImageRegistration1 Composition" ) File "/Users/rojinsafavi/miniconda2/lib/python2.7/site-packages/SimpleITK/SimpleITK.py", line 7887, in Show return _SimpleITK.Show(*args, **kwargs) RuntimeError: Exception thrown in SimpleITK Show: /scratch/dashboard/SimpleITK-OSX10.6-x86_64-pkg/SimpleITK/Code/IO/src/sitkShow.cxx:495: sitk::ERROR: No appropriate executable found.

**Comment by blowekamp** [comment]
You can find some basic information about using sitk.Show here:
https://simpleitk.readthedocs.io/en/master/Examples/ImageViewing/Documentation.html

Please ensure this is working before trying more advanced examples.

**Comment by SamuelVilz** [comment]
The link's outdated. I think, this is the new one: https://simpleitk.readthedocs.io/en/master/link_ImageViewing_docs.html

**Comment by ctorti** [comment]
> 
> 
> You can find some basic information about using sitk.Show here:
> https://simpleitk.readthedocs.io/en/master/Examples/ImageViewing/Documentation.html
> 
> Please ensure this is working before trying more advanced examples.

I had issues so took @blowekamp 's advice and tried the basic example.  I ran the following lines in Anaconda Jupyter:

`grid_image = sitk.GridSource(outputPixelType=sitk.sitkUInt16, size=(512,512),`
                             `sigma=(0.1,0.1), gridSpacing=(20.0,20.0))`

`sitk.Show(grid_image, title = "grid using Show function", debugOn = True)`

`image_viewer = sitk.ImageViewer()`
`image_viewer.SetTitle('grid using ImageViewer class')`

`image_viewer.Execute(grid_image)`

The grid opened in Fiji but the kernel seemed to get stuck.  I couldn't interrupt it - I had to restart the kernel.

I didn't execute the other lines ("Change viewer and display again") because I don't know what those lines are for, and they appear to apply to ITK-SNAP (which I don't have).

Any advice out there please?

**Comment by zivy** [comment]
Hello @ctorti,

Welcome to SimpleITK!

Is the kernel hanging after the call to `sitk.Show` but before invoking the `image_viewer`? This was an issue with older SimpleITK distributions on windows. The use of `image_viewer` should work.

In any case, please let us know your operating system and SimpleITK version (`print(sitk.Version())`).

You could also install the latest pre-release version of SimpleITK and let us know if the problem exists there too (we are working towards a major release in the near future):
```
pip install --upgrade --pre SimpleITK --find-links https://github.com/SimpleITK/SimpleITK/releases/tag/latest
```

**Comment by ctorti** [comment]
Hi @zivy thanks for your support.

I'm running v4.13 on Win10 64-bit.   I should say that I'm actually running a compiled build of SimpleElastix.  My understanding is that SimpleElastix has some wrapper functions intended to simplify SimpleITK.  

That said, so far I've been unable to obtain any successful 3D registration results in SimpleElastix but I've made minor progress with SimpleITK.  Oddly SimpleElastix seemed fine in 2D (at least for some combinations of image resolutions, pixel spacing, etc.).  

My assumption is that the non-SimpleElastix add-ons (i.e. the core SimpleITK functions) should work as they would do from a SimpleITK build.  The caveat being that (I'm guessing) the SimpleElastix updates are staggered behind SimpleITK updates.

Returning to the issue I was having with Fiji causing the kernel to hang - I decided to stick with sitk.GetArrayFromImage() + matplotlib rather than using Fiji.  I find it very useful to work in Jupyter notebooks so that I have a record of what I've done, how, what worked, what failed, etc.

So for the time being I'll not concern myself with the issue I experienced with Fiji.  In fact I've got plenty of issues in learning how to use SimpleITK/SimpleElastix.

Thanks again!

**Comment by zivy** [comment]
Hi @ctorti ,

Thanks for the clarification. I suspect you are correct in the assumption that  SimpleITK within SimpleElastix is lagging behind the main SimpleITK development.

With respect to notebooks, we are big fans of them too. If your registration needs are not as sophisticated as those provided by SimpleElastix you may benefit from our Registration notebooks that are part of [our notebook repository](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks) (series of notebooks starting with 6*).  Possibly just the GUI components if your registration needs are more complex.
