### ISSUE TITLE
How to pad image?

### ISSUE THREAD

**Issue by HyunjiEllenPak** [SimpleITK/SimpleITK#736]
Hi, I'm happy to use SimpleITK.
I have a question about ResampleImageFiler class to do "image padding". I'd like to add padding to the original image, putting the original image into the center position of the padded image(Fig2) 
When I tried with the code below, I got the padded image where the original image was at the left upper position(Fig1). It's not what I want.
![image](https://user-images.githubusercontent.com/16814077/56792347-639fe980-6844-11e9-8778-577b2243ce03.png)
[FIg1]
![image](https://user-images.githubusercontent.com/16814077/56792450-93e78800-6844-11e9-9ed7-473a1956c061.png)
[Fig2]
My code is below. I think if I adjusted some parameter, I would get the right result. But I don't know which. How can I get the right result? 
![image](https://user-images.githubusercontent.com/16814077/56792937-be861080-6845-11e9-8f2c-8765ece01fe0.png)

**Comment by blowekamp** [comment]
Please review the [fundamental concepts](https://simpleitk.readthedocs.io/en/master/Documentation/docs/source/fundamentalConcepts.html) of SimpleITK Images. Specifically, how images and pixel exist in physical space.

You have correctly propagated the image's direction and spacing however the output origin needs to be shifted. This can easily be done in index space then converted into physical space with something like:
```
output_origin_index = image.TransformContinuousIndexToPhysicalPoint ([-s/2.0 for s in shape])
```

Alternatively, a sitk::TranslationTrasform could be used instead of the identity. But this would move the physical location of the pixels which usually not what is intended when "padding".

**Comment by zivy** [comment]
Hello @HyunjiEllenPak ,

Possibly also look at the [PasteImageFilter](https://itk.org/SimpleITKDoxygen/html/classitk_1_1simple_1_1PasteImageFilter.html) which is computationally more efficient than resampling.

If the padding is done in the context of deep learning / data augmentation [this notebook](https://github.com/InsightSoftwareConsortium/SimpleITK-Notebooks/blob/master/Python/70_Data_Augmentation.ipynb) may be of interest.

**Comment by blowekamp** [comment]
I believe your question has been addressed. Please feel free to post back with the solution for your problem.
