### ISSUE TITLE
Pythonic slicing of 4D images are not supported.

### ISSUE THREAD

**Issue by PatrikBrynolfsson** [SimpleITK/SimpleITK#765]
It is possible to slice an image like so:
`img3D[:,:,5]` or `img3D[0:8,2:5,0:1]` which is VERY convenient! However, if i use JoinSeries to create a 4D image, the slicing does not work anymore:
```
img4D = sitk.JoinSeries(img3D,img3D)
img4D[:,:,:,0]

IndexError: invalid index
```
This would be great to have in 4D as well!

**Comment by blowekamp** [comment]
It looks like a couple for the underlying filter, the `SlicerImageFilter` and the `ExtractImageFilter` are not currently compiled for 4D images to work with the Python slicing index. This appears to have been an oversight.

**Comment by PatrikBrynolfsson** [comment]
I tried to apply a few filters on 4D images, with no success. Both the MedianImageFilter and the DiscreteGaussianFilter gave similar errors:

`sitk::ERROR: Pixel type: 64-bit float is not supported in 4D by class itk::simple::DiscreteGaussianImageFilter or SimpleITK compiled with SimpleITK_4D_IMAGES set to OFF.`

Is it possible that most filters are note compiled for 4D support? Is this an easy fix?

**Comment by blowekamp** [comment]
Applying a `Median` filter to a complex image does not make sense because there is no convention ordering the complex numbers to define a median.

The `exp` function is [not defined](http://www.cplusplus.com/reference/cmath/exp/) for complex number is C++.

SimpleITK does have constrains on compilation and binary size when considering instantiating more filters with more image types. A Gaussian filter or a convolution with a scalar is ell defined, but it is also the same as computing the convolution on the component of the complex number independently. That is if you do `ComplexToReal` and `ComplexToImaginary` then run the filter on each component followed by joining them with the `RealAndImaginary` filter should should be good to go.

Please keep bug issues focused on the specific topic.

**Comment by PatrikBrynolfsson** [comment]
Hello blowenkamp,

I think you mixed up two different issues. I'm merely trying to apply filters to 4D images, created by using the JoinSeries filter. These images are NOT complex images, they are float 64 images, as seen in the error message I posted. Since you answered that the slicing error was due to two filters not being compiled for 4D images, and it seems to me that more filters are in fact not compiled for 4D images I figured it was the correct issue to post in. :)

**Comment by blowekamp** [comment]
Quite right!

Still, SimpleITK does have constrains on compilation time and binary size when considering instantiating more filters with more image dimensions. Initially it was just 2D and 3D, then 4D IO added later. The `ExtractImageFilter` and the `JoinSeries` were added as complements of each other, so that one could read higher dimensional  images ( time series ) and extract the needed sub volume to process. I think added proper support for slicing index operator in Python is similar operations. 

If all filters were instantiated for 4D image the library would be about 30% longer along with the compilations time. The internal architecture readily supports 4D, and you'd get most of the filters simply by adding a line [here](https://github.com/SimpleITK/SimpleITK/blob/a642bcceb7391573d52d4731ebd734f2e0682d4c/ExpandTemplateGenerator/Components/ConstructorMemberFunctionSetup.cxx.in#L8) if you wanted to compile it your self.
