### ISSUE TITLE
Python pip wheel for Mac

### ISSUE THREAD

**Issue by chsasank** [SimpleITK/SimpleITK#77]
Hi,

From [wiki](https://itk.org/Wiki/SimpleITK/GettingStarted) ,
>The pip package manager should automatically find the correct package for MS Windows and GNU Linux if your version is supported. For Apple OS X you need to manually specify:
` pip install https://sourceforge.net/projects/simpleitk/files/SimpleITK/0.10.0/Python/SimpleITK-0.10.0-cp27-cp27m-macosx_10_6_intel.whl`

However this will work only for python 2.7. I get the following error if used with python 3.5:
```bash
$ pip install https://sourceforge.net/projects/simpleitk/files/SimpleITK/0.10.0/Python/SimpleITK-0.10.0-cp27-cp27m-macosx_10_6_intel.whl
SimpleITK-0.10.0-cp27-cp27m-macosx_10_6_intel.whl is not a supported wheel on this platform.
```

Why are the wheels for mac not uploaded to pypi? Uploading them should enhance the UX.

Thanks,
Sasank.

**Comment by blowekamp** [comment]
Unfortunately there are only 2.7 binary wheels for native OS X. This works both for the system Python and the official Python.org distribution. There are binaries for 3.5 for the Anaconda Python distribution.

The OS X wheels are too big for pipy. According to the PEP, the "intel" wheel tag indicates that the binary should be a "fat" binary containing both the i386 and x86_64 architectures. This is what makes the binary 2X bigger that other platforms.

We had been using the a Download URL, to reference the source forge links. But pip no longer supports this feature.

There have been some nice advances with pip regarding the OS X and wheel support in the past year, which enabled multi-versions of OS X to easily work. I have been hoping that pip would learn that "x86_64" is compatible with "intel" so that correctly labels wheels can be produced and i386 can be dropped in the fat binary.

There is a coming release where we will include Python 3.5 of OSX.

**Comment by thomasaarholt** [comment]
Can I ask about status on this? I'm considering using SimpleITK for image registration over at the Hyperspy community, but a fair number of us are using Macs, and it wouldn't make sense to begin development if we can't use it as a dependency.

Would conda work instead of pip?

**Comment by blowekamp** [comment]
We expect that for the 1.0 release we will be able to get the extra space needed with the new [warehouse](https://pypi.org) backend for pipy, and everything should work well with `pip install SimpleITK`. Currently you have to jump through a couple command line argument hoops to get the package:
```
$ pip install --trusted-host itk.org -f https://itk.org/SimpleITKDoxygen/html/PyDownloadPage.html SimpleITK
```

There are some problems we are trying to work on with condo-forge, but we have the binaries up on conda.anaconda.org, so the following works:

```
$ conda install -c https://conda.anaconda.org/simpleitk SimpleITK
```

Details for obtaining SimpleITK on a variety of platforms is on the [wiki](https://itk.org/Wiki/SimpleITK/GettingStarted#Generic_Distribution). We currently working on improving this for the upcoming 1.0 release, we tagged v1.0rc1 just last week.

**Comment by blowekamp** [comment]
After further research, I create a OS X wheel name: SimpleITK-0.10.0.post3-cp27-cp27m-macosx_10_6_x86_64.whl

This has been uploaded to PyPi, and now "pip install SimpleITK" works for OS X Python 2.7 too.

Enjoy!

**Comment by hjmjohnson** [comment]
Brad,

 

I’m a little confused.  I am trying to test the 1.0rc release, and based on the Feb. conversations, I had thought that binaries were released.

 

I can not find 1.0rc binaries on conda-forge ( or anywhere else).  The latest release I can find is from last July.  Is that correct?

 

Thanks,

Hans

 

 

--

**Comment by blowekamp** [comment]
There were no binaries release form 1.0rc1. I expect to release wheels for r2, and wheels and anaconda packaging for rc3.

If you would like to test with Anaconda please try the Anaconda Recipe:
https://github.com/SimpleITK/SimpleITKCondaRecipe

**Comment by gbrllemarie** [comment]
Hi, is this working for OS X Sierra? pip seems to download 0.8.0 only. When I specify a specific wheel, I get a `SimpleITK-0.10.0-cp27-cp27m-macosx_10_6_intel.whl is not a supported wheel on this platform.`. I'm using `pyenv`, if that's relevant.

**Comment by blowekamp** [comment]
What version of pip are you using? Have you tried updating?

On Jul 4, 2017, at 8:01 PM, Gabby Torres <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, is this working for OS X Sierra? pip seems to download 0.8.0 only. When I specify a specific wheel, I get a SimpleITK-0.10.0-cp27-cp27m-macosx_10_6_intel.whl is not a supported wheel on this platform.. I'm using pyenv, if that's relevant.

**Comment by gbrllemarie** [comment]
I'm using pip 9.0.1

**Comment by blowekamp** [comment]
This still sound like the behavior of an older version of pip. Perhaps if you invoke pip with:
```
python -m pip install SimpleITK
```
The expected behavior will occur.

**Comment by gbrllemarie** [comment]
So I figured out that my system was having trouble linking the proper pip executable. I'm now using the right pip version, but importing the modules gives me a `Fatal Python error: PyThreadState_Get: no current thread`.

**Comment by blowekamp** [comment]
This was a problem with non-system python installations on OSX several versions ago. Please update to the latest SimpleITK 1.0 binary. This should be able to be done from a functional Python installation at the command prompt with:
'''
python -m pip install -U SimpkeITK
'''

**Comment by gbrllemarie** [comment]
```
❯ python -m pip install -U SimpkeITK
Collecting SimpkeITK
  Could not find a version that satisfies the requirement SimpkeITK (from versions: )
No matching distribution found for SimpkeITK
```

I noticed I still have 0.8.0 by the way. Not sure why pip can't find the later versions.

**Comment by blowekamp** [comment]
What python are you trying to use?

**Comment by gbrllemarie** [comment]
python 2.7.12

**Comment by blowekamp** [comment]
Who is the distributor or vender?

**Comment by gbrllemarie** [comment]
pyenv 1.0.10.

```
$ which python
/Users/jerome.indefenzo/.pyenv/shims/python

$ which pip
/Users/jerome.indefenzo/.pyenv/shims/pip

$ pip install simpleitk
Requirement already satisfied: simpleitk in /Users/jerome.indefenzo/.pyenv/versions/2.7.12/lib/python2.7/site-packages

$ pip install simpleitk==1.0.0
Collecting simpleitk==1.0.0
  Could not find a version that satisfies the requirement simpleitk==1.0.0 (from versions: 0.8.0)
No matching distribution found for simpleitk==1.0.0
```

**Comment by blowekamp** [comment]
The system python version on my OS X Sierra is "Python 2.7.10". I believe you are not using the system python, and the python you are using was obtained from another distributor such as Anaconda, Enthought, Homebrew...?

What information is printed when you run python as an interactive interpreter:
```
python -i
```

```
python -c "import distutils.util; print(distutils.util.get_platform())"
```

Perhaps you are somehow running 32-bit Python?  Then the following binary may work:
https://sourceforge.net/projects/simpleitk/files/SimpleITK/1.0.0/Python/SimpleITK-1.0.0-cp27-cp27m-macosx_10_6_intel.whl/download

It is also possibly you installation of python and pip have gotten corrupted since it appears not to be behaving as expected.
