### ISSUE TITLE
What is the framework or algorithm for WarpImageFilter or ResampleImageFilter?

### ISSUE THREAD

**Issue by wentaozhu** [SimpleITK/SimpleITK#773]
I tried to use scipy function map_coordinates to do the resample, but I find the results from simpleitk WarpImageFilter and ResampleImageFilter are different from map_coordinates function.

I have added the coordinates and swap the axes to turn the displacement field in simpleitk to deformation field in map_coordinates.

I tried different configurations sitk.sitkBSpline and order=3 in map_coordinates; sitk.sitkLinear and order = 1 in map_coordinates. 

Could you please give me some advices? 

Thank you!

**Comment by zivy** [comment]
Hi @wentaozhu ,

I am not familiar with scipy's map_coordinates but it looks like it works on a numpy array. This implicitly assumes an isotropic image with unit size spacing and identity direction cosine matrix. This is not in line with the concept of an image in simpleitk as [described here](https://simpleitk.readthedocs.io/en/master/Documentation/docs/source/fundamentalConcepts.html). 

Please check your simpleitk image to see if the implicit scipy assumptions hold. I suspect they don't.

Please close the question if this addresses the issue or provide additional details so that we can further help you.

**Comment by wentaozhu** [comment]
Thank you! I solved it.
