### ISSUE TITLE
How to visualize the displacement field of BSpline registration?

### ISSUE THREAD

**Issue by h1310321230** [SimpleITK/SimpleITK#932]
I want to compute the Jacobian determinant of displacement field using code ''jb = sitk.DisplacementFieldJacobianDeterminant(outTx.GetDisplacementField())"  for Demons registration. I do not know it  is  right or not. Please tell me if this is right or wrong.

And, I do this same way for BSpline registation. But, it has mistakes. If I want to get Jacobian determinant of displacement field of BSpline, what should I do?

**Comment by zivy** [comment]
Hello @h1310321230,

What you are doing is fine for the displacement field, the output from the Demons algorithm.

For BSpline transform, or any other transformation, you will need to convert to displacement field:

```
sitk.TransformToDisplacementField(bspline_transform, 
                                  sitk.sitkVectorFloat64,
                                  fixed_image.GetSize(),
                                  fixed_image.GetOrigin(),
                                  fixed_image.GetSpacing(),
                                  fixed_image.GetDirection())
```
The title of your question asks about visualization and not about the computation of the Jacobian determinant, so I assume you have two questions?

To visualize a deformation field you can use 3D Slicer, as described [here](https://discourse.slicer.org/t/visualize-deformation-field/1552).

If this answers your questions, please close the issue, otherwise please provide additional details/clarifications.

**Comment by h1310321230** [comment]
Thank you very much. 
I want to visualize the Jacobian Determinant like this image. How to write the _codes?
![QQ截图20191228160217](https://user-images.githubusercontent.com/18464627/71540891-ae51a280-298b-11ea-81a3-9abc76dc72ff.png)

**Comment by zivy** [comment]
Ok, got it. The code below, and the display of multiple images [matplotlib example](https://matplotlib.org/3.1.1/gallery/images_contours_and_fields/multi_image.html#sphx-glr-gallery-images-contours-and-fields-multi-image-py) should do what you want:

```
#random 3D displacement field in numpy array
np_displacement_field = np.random.randn(20,256,256,3)

#Convert the numpy array to a 256x256x20 image with each pixel 
#being a 3D vector and compute the jacobian determinant volume
sitk_displacement_field = sitk.GetImageFromArray(np_displacement_field, isVector=True)
jacobian_det_volume = sitk.DisplacementFieldJacobianDeterminant(sitk_displacement_field)

#To show all the slices using the same color range you need to get the min
#and max of the whole volume and use matplotlib and numpy for display
jacobian_det_np_arr = sitk.GetArrayViewFromImage(jacobian_det_volume)

# Iterating over the slices
for i in range(1,jacobian_det_np_arr.shape[0]+1):
   dat = jacobian_det_np_arr[i-1,:,:]

```

**Comment by h1310321230** [comment]
Thank you very much.
